apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api-svc-v1-0
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80