apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: todo-api-policy
spec:
  targets:
  - name: todo-api-svc
  peers:
  - mtls: {}
#  origins:
#  - jwt:
#      issuer: http://keycloak/auth/realms/test
#      jwksUri: http://keycloak/auth/realms/test/protocol/openid-connect/certs
#  principalBinding: USE_ORIGIN